// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Joeybuilt LLC

import Link from 'next/link'

export const metadata = {
    title: 'Terms of Service | Plexo',
    description: 'Plexo Terms of Service',
}

export default function TermsPage() {
    return (
        <main className="mx-auto max-w-2xl px-6 py-16">
            <h1 className="text-3xl font-bold text-text-primary mb-2">Terms of Service</h1>
            <p className="text-sm text-text-muted mb-8">Last updated: April 2026</p>

            <div className="prose prose-sm prose-invert max-w-none space-y-6 text-text-secondary">
                <section>
                    <h2 className="text-lg font-semibold text-text-primary">1. Acceptance of Terms</h2>
                    <p>By accessing or using Plexo, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the service.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">2. Description of Service</h2>
                    <p>Plexo is an AI operations platform that provides agent orchestration, task management, and workflow automation capabilities. The service may be self-hosted or accessed via a managed deployment.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">3. User Accounts</h2>
                    <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">4. Acceptable Use</h2>
                    <p>You agree not to use the service to violate any applicable law, infringe intellectual property rights, transmit malicious code, or interfere with the operation of the service.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">5. Data and Privacy</h2>
                    <p>Your use of the service is also governed by our <Link href="/privacy" className="text-azure hover:underline">Privacy Policy</Link>. You retain ownership of data you provide to the service.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">6. AI-Generated Content</h2>
                    <p>Content generated by AI agents within Plexo is provided as-is. You are responsible for reviewing and validating any AI-generated output before relying on it.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">7. Limitation of Liability</h2>
                    <p>The service is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">8. Changes to Terms</h2>
                    <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.</p>
                </section>

                <section>
                    <h2 className="text-lg font-semibold text-text-primary">9. Contact</h2>
                    <p>For questions about these terms, contact us at legal@getplexo.com.</p>
                </section>
            </div>

            <div className="mt-12 border-t border-border pt-6">
                <Link href="/" className="text-sm text-text-muted hover:text-text-secondary transition-colors">
                    Back to home
                </Link>
            </div>
        </main>
    )
}
