// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Joeybuilt LLC

import {
    pgTable,
    uuid,
    text,
    timestamp,
    boolean,
    integer,
    real,
    jsonb,
    pgEnum,
    date,
    index,
    uniqueIndex,
    primaryKey,
    varchar,
} from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

// ── Enums ────────────────────────────────────────────────────────

export const userRoleEnum = pgEnum('user_role', ['admin', 'member'])
export const memberRoleEnum = pgEnum('member_role', ['owner', 'admin', 'member', 'viewer'])

export const channelTypeEnum = pgEnum('channel_type', [
    'telegram',
    'slack',
    'discord',
    'whatsapp',
    'signal',
    'matrix',
    'irc',
    'webchat',
])

export const taskTypeEnum = pgEnum('task_type', [
    'coding',
    'deployment',
    'research',
    'ops',
    'opportunity',
    'monitoring',
    'report',
    'online',
    'automation',
    'writing',
    'general',
    'data',
    'marketing',
])

export type TaskType = (typeof taskTypeEnum.enumValues)[number]

export const taskStatusEnum = pgEnum('task_status', [
    'queued',
    'claimed',
    'running',
    'complete',
    'blocked',
    'cancelled',
])

export type TaskStatus = (typeof taskStatusEnum.enumValues)[number]

export const taskSourceEnum = pgEnum('task_source', [
    'telegram',
    'slack',
    'discord',
    'scanner',
    'github',
    'cron',
    'dashboard',
    'api',
    'extension',
    'sentry',
])

export const sprintStatusEnum = pgEnum('sprint_status', [
    'planning',
    'running',
    'finalizing',
    'complete',
    'failed',
    'cancelled',
])

export const sprintTaskStatusEnum = pgEnum('sprint_task_status', [
    'queued',
    'running',
    'complete',
    'blocked',
    'failed',
])

export const pluginTypeEnum = pgEnum('plugin_type', [
    'agent',
    'skill',
    'channel',
    'tool',
    'mcp-server',
])

export const memoryTypeEnum = pgEnum('memory_type', [
    'task',
    'incident',
    'session',
    'pattern',
])

export const docTypeEnum = pgEnum('doc_type', [
    'spec',
    'features',
    'decisions',
    'agents',
    'readme',
    'custom',
])

export const authTypeEnum = pgEnum('auth_type', [
    'oauth2',
    'api_key',
    'webhook',
    'none',
])

export const connectionStatusEnum = pgEnum('connection_status', [
    'active',
    'error',
    'expired',
    'disconnected',
])

export const calibrationEnum = pgEnum('calibration', [
    'over',
    'correct',
    'under',
])

export const cronRunStatusEnum = pgEnum('cron_run_status', [
    'success',
    'failure',
])

export const rsiStatusEnum = pgEnum('rsi_status', [
    'pending',
    'approved',
    'rejected',
])

export const sprintFileEventTypeEnum = pgEnum('sprint_file_event_type', ['lock', 'conflict', 'change', 'build_error', 'ts_error'])
export const sprintPatternTypeEnum = pgEnum('sprint_pattern_type', ['conflict_hotspot', 'complexity_signal', 'recurring_error'])


export const rsiRiskEnum = pgEnum('rsi_risk', [
    'low',
    'medium',
    'high',
])

// ── Users ────────────────────────────────────────────────────────
// Auth is handled by the shared Supabase project (joeybuilt-platform).
// The `id` is the Supabase auth.users.id UUID — set explicitly on upsert,
// never auto-generated by Plexo.

export const users = pgTable('users', {
    id: uuid('id').primaryKey(),           // Supabase auth.users.id — no defaultRandom()
    email: text('email').unique().notNull(),
    emailVerified: timestamp('email_verified', { mode: 'date' }),
    name: text('name'),
    image: text('image'),
    role: userRoleEnum('role').default('member').notNull(),
    isSuperAdmin: boolean('is_super_admin').default(false).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
})

// ── Core Tables ──────────────────────────────────────────────────

export const workspaces = pgTable('workspaces', {
    id: uuid('id').defaultRandom().primaryKey(),
    name: text('name').notNull(),
    ownerId: uuid('owner_id')
        .notNull()
        .references(() => users.id),
    settings: jsonb('settings').default('{}').notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
})

export const workspaceKeyShares = pgTable('workspace_key_shares', {
    id: text('id').primaryKey(),  // ulid
    sourceWsId: uuid('source_ws_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    targetWsId: uuid('target_ws_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    providerKey: text('provider_key').notNull(),  // 'openai' | 'anthropic' | etc.
    grantedBy: uuid('granted_by')
        .notNull()
        .references(() => users.id),
    grantedAt: timestamp('granted_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('key_shares_source_idx').on(table.sourceWsId),
    index('key_shares_target_idx').on(table.targetWsId),
    uniqueIndex('key_shares_unique_idx').on(table.sourceWsId, table.targetWsId, table.providerKey),
])

export const channels = pgTable('channels', {
    id: uuid('id').defaultRandom().primaryKey(),

    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    type: channelTypeEnum('type').notNull(),
    name: text('name').notNull(),
    config: jsonb('config').notNull(),
    enabled: boolean('enabled').default(true).notNull(),
    lastMessageAt: timestamp('last_message_at', { mode: 'date' }),
    errorCount: integer('error_count').default(0).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('channels_workspace_idx').on(table.workspaceId),
])

export const tasks = pgTable('tasks', {
    id: text('id').primaryKey(), // ulid
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    type: taskTypeEnum('type').notNull(),
    status: taskStatusEnum('status').default('queued').notNull(),
    priority: integer('priority').default(1).notNull(),
    source: taskSourceEnum('source').notNull(),
    project: text('project'),
    // projectId links this task to the sprint/project that spawned it.
    // Null for standalone tasks (chat, cron, API). ON DELETE SET NULL so
    // deleting a sprint doesn't cascade-delete the task history.
    projectId: text('project_id').references((): any => sprints.id, { onDelete: 'set null' }), // eslint-disable-line @typescript-eslint/no-explicit-any
    parentId: text('parent_id').references((): any => tasks.id), // eslint-disable-line @typescript-eslint/no-explicit-any -- self-ref
    context: jsonb('context').notNull(),
    qualityScore: real('quality_score'),
    confidenceScore: real('confidence_score'),
    tokensIn: integer('tokens_in'),
    tokensOut: integer('tokens_out'),
    costUsd: real('cost_usd'),
    /** Max USD this task may spend. null = use workspace default. */
    costCeilingUsd: real('cost_ceiling_usd'),
    /** Max output tokens. null = no per-task token cap. Maps to generateText maxTokens. */
    tokenBudget: integer('token_budget'),
    promptVersion: text('prompt_version'),
    outcomeSummary: text('outcome_summary'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
    claimedAt: timestamp('claimed_at', { mode: 'date' }),
    completedAt: timestamp('completed_at', { mode: 'date' }),
}, (table) => [
    index('tasks_workspace_status_idx').on(table.workspaceId, table.status),
    index('tasks_workspace_project_idx').on(table.workspaceId, table.project),
    index('tasks_project_id_idx').on(table.projectId),
])

/**
 * conversations — chat/channel interaction log.
 * Separate from tasks: a conversation is a logged exchange, not an agent work item.
 * Tasks are only created when a user explicitly triggers agent execution.
 */
export const conversations = pgTable('conversations', {
    id: text('id').primaryKey(), // ulid
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    sessionId: text('session_id'),
    source: text('source').notNull().default('dashboard'), // dashboard | telegram | slack | discord | api | widget
    message: text('message').notNull(),
    reply: text('reply'),
    errorMsg: text('error_msg'),
    status: text('status').notNull().default('complete'), // complete | failed | pending
    intent: text('intent'), // CONVERSATION | TASK | PROJECT — classifier output
    taskId: text('task_id').references((): any => tasks.id, { onDelete: 'set null' }), // eslint-disable-line @typescript-eslint/no-explicit-any
    /**
     * Origin channel reference — stored when the conversation started in an external channel.
     * Shape: { channel: 'telegram'|'slack'|'discord', channelId: string, chatId: string }
     * Used to route web-initiated replies back to the originating channel.
     */
    channelRef: jsonb('channel_ref').$type<{ channel: string; channelId: string; chatId: string } | null>().default(null),
    attachments: jsonb('attachments').$type<{ url: string; type: string; alt?: string }[]>().default([]).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('conversations_workspace_idx').on(table.workspaceId),
    index('conversations_workspace_created_idx').on(table.workspaceId, table.createdAt),
    index('conversations_session_idx').on(table.sessionId),
])

export const taskSteps = pgTable('task_steps', {
    id: uuid('id').defaultRandom().primaryKey(),
    taskId: text('task_id')
        .notNull()
        .references(() => tasks.id, { onDelete: 'cascade' }),
    stepNumber: integer('step_number').notNull(),
    model: text('model'),
    tokensIn: integer('tokens_in'),
    tokensOut: integer('tokens_out'),
    toolCalls: jsonb('tool_calls'),
    outcome: text('outcome'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('task_steps_task_idx').on(table.taskId),
])

export const sprints = pgTable('sprints', {
    id: text('id').primaryKey(), // ulid
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    repo: text('repo'),  // null for non-code projects
    category: text('category').notNull().default('code'), // code | research | writing | ops | data | marketing | general
    metadata: jsonb('metadata').notNull().default('{}'), // category-specific structured fields
    request: text('request').notNull(),
    status: sprintStatusEnum('status').default('planning').notNull(),
    totalTasks: integer('total_tasks').default(0).notNull(),
    completedTasks: integer('completed_tasks').default(0).notNull(),
    failedTasks: integer('failed_tasks').default(0).notNull(),
    conflictCount: integer('conflict_count').default(0).notNull(),
    qualityScore: real('quality_score'),
    totalTokens: integer('total_tokens'),
    costUsd: real('cost_usd'),
    /** Max USD the entire project (all tasks combined) may spend. null = unlimited within workspace ceiling. */
    costCeilingUsd: real('cost_ceiling_usd'),
    wallClockMs: integer('wall_clock_ms'),
    plannerIterations: integer('planner_iterations').default(0).notNull(),
    featuresCompleted: jsonb('features_completed').default('[]').notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
    completedAt: timestamp('completed_at', { mode: 'date' }),
}, (table) => [
    index('sprints_workspace_idx').on(table.workspaceId),
])

export const sprintTasks = pgTable('sprint_tasks', {
    id: text('id').primaryKey(), // ulid
    sprintId: text('sprint_id')
        .notNull()
        .references(() => sprints.id, { onDelete: 'cascade' }),
    description: text('description').notNull(),
    scope: jsonb('scope').notNull(), // string[]
    acceptance: text('acceptance').notNull(),
    branch: text('branch').notNull(),
    priority: integer('priority').default(1).notNull(),
    status: sprintTaskStatusEnum('status').default('queued').notNull(),
    handoff: jsonb('handoff'),
    workerContainerId: text('worker_container_id'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
    completedAt: timestamp('completed_at', { mode: 'date' }),
}, (table) => [
    index('sprint_tasks_sprint_idx').on(table.sprintId),
])

export const sprintHandoffs = pgTable('sprint_handoffs', {
    id: text('id').primaryKey(),
    sprintId: text('sprint_id')
        .notNull()
        .references(() => sprints.id, { onDelete: 'cascade' }),
    taskId: text('task_id')
        .references(() => sprintTasks.id, { onDelete: 'cascade' }),
    summary: text('summary').notNull(),
    filesChanged: jsonb('files_changed').default('[]').notNull(),
    concerns: jsonb('concerns').default('[]').notNull(),
    suggestions: jsonb('suggestions').default('[]').notNull(),
    tokensUsed: integer('tokens_used').default(0).notNull(),
    toolCalls: integer('tool_calls').default(0).notNull(),
    durationMs: integer('duration_ms').default(0).notNull(),
    suspicious: boolean('suspicious').default(false).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('sprint_handoffs_sprint_idx').on(table.sprintId),
])

export const sprintFileEvents = pgTable('sprint_file_events', {
    id: text('id').primaryKey(),
    sprintId: text('sprint_id')
        .notNull()
        .references(() => sprints.id, { onDelete: 'cascade' }),
    repo: text('repo').notNull(),
    eventType: sprintFileEventTypeEnum('event_type').notNull(),
    filePath: text('file_path').notNull(),
    message: text('message'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('sprint_file_events_sprint_idx').on(table.sprintId),
    index('sprint_file_events_repo_path_idx').on(table.repo, table.filePath),
])

export const sprintPatterns = pgTable('sprint_patterns', {
    id: text('id').primaryKey(),
    repo: text('repo').notNull(),
    patternType: sprintPatternTypeEnum('pattern_type').notNull(),
    subject: text('subject').notNull(),
    occurrences: integer('occurrences').default(1).notNull(),
    avgDurationMs: integer('avg_duration_ms'),
    avgQuality: real('avg_quality'),
    data: jsonb('data').default('{}').notNull(),
    lastSeenAt: timestamp('last_seen_at', { mode: 'date' }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('sprint_patterns_repo_idx').on(table.repo),
    uniqueIndex('sprint_patterns_repo_type_subject_idx').on(table.repo, table.patternType, table.subject),
])

export const plugins = pgTable('plugins', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    // Scoped package name — must match @scope/name format (§3.1)
    name: text('name').notNull(),
    version: text('version').notNull(),
    type: pluginTypeEnum('type').notNull(),
    // Kapsel spec version this manifest targets (e.g. '0.2.0')
    kapselVersion: text('kapsel_version').notNull().default('0.2.0'),
    // Relative path to the entry point (§3.1)
    entry: text('entry').notNull(),
    // Full kapsel.json contents (validated on install per §3.3)
    kapselManifest: jsonb('kapsel_manifest').notNull(),
    enabled: boolean('enabled').default(false).notNull(),
    // Extension-private settings storage (injected as sdk.storage via Redis)
    settings: jsonb('settings').default('{}').notNull(),
    installedAt: timestamp('installed_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('plugins_workspace_idx').on(table.workspaceId),
    // Unique per workspace — enables upsert during re-synthesis
    uniqueIndex('plugins_workspace_name_uq').on(table.workspaceId, table.name),
])

export const dashboardCards = pgTable('dashboard_cards', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
        .notNull()
        .references(() => users.id, { onDelete: 'cascade' }),
    cardType: text('card_type').notNull(),
    position: jsonb('position').notNull(), // { x, y, w, h }
    config: jsonb('config').default('{}').notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('dashboard_cards_user_idx').on(table.userId, table.workspaceId),
])

export const cronJobs = pgTable('cron_jobs', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    schedule: text('schedule').notNull(),
    enabled: boolean('enabled').default(true).notNull(),
    lastRunAt: timestamp('last_run_at', { mode: 'date' }),
    lastRunStatus: cronRunStatusEnum('last_run_status'),
    consecutiveFailures: integer('consecutive_failures').default(0).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
})

export const memoryEntries = pgTable('memory_entries', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    type: memoryTypeEnum('type').notNull(),
    content: text('content').notNull(),
    /** 
     * AI-generated shorthand/facts/principles extraction. 
     * Minimizes token consumption when injected into agent prompts.
     */
    shorthand: text('shorthand'),
    // pgvector column — raw SQL needed until drizzle-orm has native vector support
    // embedding: vector(1536) — added via custom migration SQL
    metadata: jsonb('metadata').default('{}').notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('memory_entries_workspace_type_idx').on(table.workspaceId, table.type),
])

export const workLedger = pgTable('work_ledger', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    taskId: text('task_id').references(() => tasks.id),
    type: text('type').notNull(),
    source: text('source').notNull(),
    tokensIn: integer('tokens_in'),
    tokensOut: integer('tokens_out'),
    costUsd: real('cost_usd'),
    qualityScore: real('quality_score'),
    confidenceScore: real('confidence_score'),
    calibration: calibrationEnum('calibration'),
    deliverables: jsonb('deliverables').default('[]').notNull(),
    wallClockMs: integer('wall_clock_ms'),
    completedAt: timestamp('completed_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('work_ledger_workspace_idx').on(table.workspaceId),
])

export const projectDocs = pgTable('project_docs', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    project: text('project').notNull(),
    type: docTypeEnum('type').notNull(),
    filename: text('filename').notNull(),
    content: text('content').notNull(),
    version: integer('version').default(1).notNull(),
    committedAt: timestamp('committed_at', { mode: 'date' }),
    commitSha: text('commit_sha'),
    autoGenerated: boolean('auto_generated').default(false).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('project_docs_workspace_project_idx').on(table.workspaceId, table.project),
])

export const connectionsRegistry = pgTable('connections_registry', {
    id: text('id').primaryKey(), // e.g. 'github', 'stripe'
    name: text('name').notNull(),
    description: text('description').notNull(),
    category: text('category').notNull(),
    logoUrl: text('logo_url'),
    authType: authTypeEnum('auth_type').notNull(),
    oauthScopes: jsonb('oauth_scopes').default('[]').notNull(),
    setupFields: jsonb('setup_fields').default('[]').notNull(),
    toolsProvided: jsonb('tools_provided').default('[]').notNull(),
    cardsProvided: jsonb('cards_provided').default('[]').notNull(),
    isCore: boolean('is_core').default(false).notNull(),
    /** True for connections auto-generated by the agent synthesizer */
    isGenerated: boolean('is_generated').default(false).notNull(),
    docUrl: text('doc_url'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
})

export const installedConnections = pgTable('installed_connections', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    registryId: text('registry_id')
        .notNull()
        .references(() => connectionsRegistry.id),
    name: text('name').notNull(),
    credentials: jsonb('credentials').notNull(), // encrypted at rest
    enabledTools: jsonb('enabled_tools').$type<string[] | null>().default(null), // null = all enabled
    scopesGranted: jsonb('scopes_granted').default('[]').notNull(),
    status: connectionStatusEnum('status').default('active').notNull(),
    lastVerifiedAt: timestamp('last_verified_at', { mode: 'date' }),
    errorDetail: text('error_detail'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    uniqueIndex('installed_connections_workspace_registry_uq').on(table.workspaceId, table.registryId),
    index('installed_connections_workspace_idx').on(table.workspaceId),
])

export const apiCostTracking = pgTable('api_cost_tracking', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    weekStart: date('week_start').notNull(),
    costUsd: real('cost_usd').default(0).notNull(),
    ceilingUsd: real('ceiling_usd').default(10).notNull(),
    alerted80: boolean('alerted_80').default(false).notNull(),
    paused: boolean('paused').default(false).notNull(),
}, (table) => [
    uniqueIndex('api_cost_workspace_week_idx').on(table.workspaceId, table.weekStart),
])

// ── Memory + self-improvement tables (Phase 6) ───────────────────

export const workspacePreferences = pgTable('workspace_preferences', {
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    key: text('key').notNull(),
    value: jsonb('value').notNull(),
    confidence: real('confidence').default(0.5).notNull(),
    evidenceCount: integer('evidence_count').default(1).notNull(),
    lastUpdated: timestamp('last_updated', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    primaryKey({ columns: [table.workspaceId, table.key] }),
    index('workspace_preferences_workspace_idx').on(table.workspaceId),
])

export const agentImprovementLog = pgTable('agent_improvement_log', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    patternType: text('pattern_type').notNull(), // failure_pattern | success_pattern | tool_preference | scope_adjustment | skill_proposal | plugin_proposal | agent_proposal
    description: text('description').notNull(),
    evidence: jsonb('evidence').default('[]').notNull(), // task IDs
    proposedChange: text('proposed_change'),
    applied: boolean('applied').default(false).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('agent_improvement_log_workspace_idx').on(table.workspaceId),
])

// ── Phase 11 — Workspace membership + invites ─────────────────────────────────

export const workspaceMembers = pgTable('workspace_members', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
        .notNull()
        .references(() => users.id, { onDelete: 'cascade' }),
    role: memberRoleEnum('role').default('member').notNull(),
    invitedByUserId: uuid('invited_by_user_id').references(() => users.id),
    joinedAt: timestamp('joined_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    uniqueIndex('workspace_members_workspace_user_idx').on(table.workspaceId, table.userId),
    index('workspace_members_workspace_idx').on(table.workspaceId),
    index('workspace_members_user_idx').on(table.userId),
])

export const workspaceInvites = pgTable('workspace_invites', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    token: text('token').notNull().unique(),
    invitedEmail: text('invited_email'),
    role: memberRoleEnum('role').default('member').notNull(),
    invitedByUserId: uuid('invited_by_user_id')
        .notNull()
        .references(() => users.id),
    expiresAt: timestamp('expires_at', { mode: 'date' }).notNull(),
    usedAt: timestamp('used_at', { mode: 'date' }),
    usedByUserId: uuid('used_by_user_id').references(() => users.id),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    uniqueIndex('workspace_invites_token_idx').on(table.token),
    index('workspace_invites_workspace_idx').on(table.workspaceId),
])

// ── Phase 21 — Kapsel Extension Registry (§12) ──────────────────────────────
// Public listing of extensions available for installation.
// Scoped: entries belong to a workspace (org/user namespace).

export const kapselRegistry = pgTable('kapsel_registry', {
    id: uuid('id').defaultRandom().primaryKey(),
    /** Scoped package name e.g. @acme/stripe-monitor */
    name: text('name').notNull().unique(),
    /** Display name */
    displayName: text('display_name').notNull(),
    /** Short description */
    description: text('description').notNull(),
    /** Publisher workspace or user handle */
    publisher: text('publisher').notNull(),
    /** Latest published version */
    latestVersion: text('latest_version').notNull(),
    /** All published versions (ordered newest first) */
    versions: jsonb('versions').$type<string[]>().default([]).notNull(),
    /** Full kapsel.json manifest for the latest version */
    manifest: jsonb('manifest').notNull(),
    /** Tags for discovery */
    tags: text('tags').array().default([]).notNull(),
    /** Install count (approximate, not trusted for billing) */
    installCount: integer('install_count').default(0).notNull(),
    /** Deprecated: set by publisher, hidden from search */
    deprecated: boolean('deprecated').default(false).notNull(),
    /** SHA-256 of the published bundle (for integrity verification) */
    checksum: text('checksum'),
    /** Source repository URL */
    repositoryUrl: text('repository_url'),
    publishedAt: timestamp('published_at', { mode: 'date' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('kapsel_registry_name_idx').on(table.name),
    index('kapsel_registry_publisher_idx').on(table.publisher),
    index('kapsel_registry_deprecated_idx').on(table.deprecated),
])

// ── Phase 13 — Audit log ──────────────────────────────────────────────────────

export const auditLog = pgTable('audit_log', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').references(() => users.id),  // null for system events
    action: text('action').notNull(),                    // e.g. 'member.add', 'plugin.install', 'task.create'
    resource: text('resource').notNull(),                // table name or resource type
    resourceId: text('resource_id'),                     // optional target entity ID
    metadata: jsonb('metadata').default('{}').notNull(), // extra context (role, email, etc.)
    ip: text('ip'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('audit_log_workspace_idx').on(table.workspaceId),
    index('audit_log_action_idx').on(table.action),
    index('audit_log_created_idx').on(table.createdAt),
])

// ── Phase 5 — Agent Behavior Configuration ───────────────────────────────────

export const ruleTypeEnum = pgEnum('rule_type', [
    'safety_constraint',
    'operational_rule',
    'communication_style',
    'domain_knowledge',
    'persona_trait',
    'tool_preference',
    'quality_gate',
])

export const ruleSourceEnum = pgEnum('rule_source', [
    'platform',
    'workspace',
    'project',
    'task',
])

/**
 * behavior_rules — structured agent behavior rules with inheritance.
 * Source hierarchy: platform → workspace → project → task (later wins).
 */
export const behaviorRules = pgTable('behavior_rules', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    /** null = workspace-level rule */
    projectId: uuid('project_id'),
    type: ruleTypeEnum('type').notNull(),
    /** Machine-readable key, unique within (workspace, project) scope */
    key: text('key').notNull(),
    label: text('label').notNull(),
    description: text('description').notNull().default(''),
    /** Typed value: { type: 'boolean'|'string'|'number'|'enum'|'text_block'|'json', value, ...meta } */
    value: jsonb('value').notNull(),
    /** Safety constraints cannot be deleted or toggled off */
    locked: boolean('locked').notNull().default(false),
    source: ruleSourceEnum('source').notNull().default('workspace'),
    /** Self-referential: which parent rule this overrides */
    overridesRuleId: uuid('overrides_rule_id'),
    tags: text('tags').array().notNull().default(sql`'{}'`),
    /** Soft delete */
    deletedAt: timestamp('deleted_at', { mode: 'date' }),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('behavior_rules_workspace_idx').on(table.workspaceId),
    index('behavior_rules_project_idx').on(table.projectId),
    index('behavior_rules_type_idx').on(table.type),
    index('behavior_rules_deleted_idx').on(table.deletedAt),
])

/**
 * behavior_groups — card groups shown in UI (seeded, not user-editable).
 */
export const behaviorGroups = pgTable('behavior_groups', {
    id: text('id').primaryKey(), // e.g. 'safety', 'communication'
    label: text('label').notNull(),
    description: text('description').notNull().default(''),
    icon: text('icon').notNull().default('Circle'),
    ruleTypes: ruleTypeEnum('rule_types').array().notNull(),
    locked: boolean('locked').notNull().default(false),
    color: text('color').notNull().default('zinc'),
    displayOrder: integer('display_order').notNull().default(0),
})

// ── MCP Tokens ──────────────────────────────────────────────────────────────
// Hashed API tokens for MCP transport. Raw value shown once on creation.
// SHA-256 with per-token random salt. type='mcp' required for MCP transport.

export const mcpTokens = pgTable('mcp_tokens', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    tokenHash: text('token_hash').notNull(),   // SHA-256(raw + salt)
    tokenSalt: text('token_salt').notNull(),   // random 32-byte hex
    scopes: text('scopes').array().notNull().default(sql`'{}'`),
    type: text('type').notNull().default('mcp'),
    revoked: boolean('revoked').notNull().default(false),
    expiresAt: timestamp('expires_at', { mode: 'date' }),
    lastUsedAt: timestamp('last_used_at', { mode: 'date' }),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('mcp_tokens_workspace_idx').on(table.workspaceId),
    index('mcp_tokens_hash_idx').on(table.tokenHash),
])

/**
 * behavior_snapshots — version history, one per task/sprint start or manual preview.
 */
export const behaviorSnapshots = pgTable('behavior_snapshots', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id'),
    /** Full resolved rule set at time of snapshot */
    snapshot: jsonb('snapshot').notNull(),
    /** Compiled system prompt fragment from this snapshot */
    compiledPrompt: text('compiled_prompt').notNull().default(''),
    /** 'manual' | 'task_start' | 'sprint_start' */
    triggeredBy: text('triggered_by').notNull().default('manual'),
    /** Task/sprint ID that triggered this snapshot */
    triggerResourceId: text('trigger_resource_id'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('behavior_snapshots_workspace_idx').on(table.workspaceId),
    index('behavior_snapshots_created_idx').on(table.createdAt),
])

// ── Sprint Logs (Real-time activity feed) ───────────────────────────────────────

export const sprintLogs = pgTable('sprint_logs', {
    id: uuid('id').defaultRandom().primaryKey(),
    sprintId: text('sprint_id')
        .notNull()
        .references(() => sprints.id, { onDelete: 'cascade' }),
    level: text('level').notNull().default('info'), // info | warn | error
    event: text('event').notNull(), // planning_start | task_queued | wave_start | task_running | task_complete | task_failed | sprint_complete | sprint_failed | conflict_detected | pr_created | budget_check
    message: text('message').notNull(),
    metadata: jsonb('metadata').default('{}').notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('sprint_logs_sprint_idx').on(table.sprintId, table.createdAt),
    index('sprint_logs_sprint_level_idx').on(table.sprintId, table.level),
])

// ── Models Knowledge Base (Automated Routing) ──────────────────────────────────
export const modelsKnowledge = pgTable('models_knowledge', {
    id: text('id').primaryKey(),
    provider: text('provider').notNull(),
    modelId: text('model_id').notNull(),
    contextWindow: integer('context_window').default(128000).notNull(),
    costPerMIn: real('cost_per_m_in').notNull(),
    costPerMOut: real('cost_per_m_out').notNull(),
    strengths: jsonb('strengths').$type<string[]>().default([]).notNull(),
    reliabilityScore: real('reliability_score').default(1.0).notNull(),
    lastSyncedAt: timestamp('last_synced_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('models_knowledge_provider_idx').on(table.provider),
    index('models_knowledge_model_idx').on(table.modelId),
])

// ── RSI (Real-Time Self-Inspection) ────────────────────────────────────────────

export const rsiProposals = pgTable('rsi_proposals', {
    id: uuid('id').defaultRandom().primaryKey(),
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    anomalyType: text('anomaly_type').notNull(),
    hypothesis: text('hypothesis').notNull(),
    proposedChange: jsonb('proposed_change').default('{}').notNull(),
    risk: rsiRiskEnum('risk').default('medium').notNull(),
    status: rsiStatusEnum('status').default('pending').notNull(),
    approvedAt: timestamp('approved_at', { mode: 'date' }),
    rejectedAt: timestamp('rejected_at', { mode: 'date' }),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('rsi_proposals_workspace_idx').on(table.workspaceId),
    index('rsi_proposals_status_idx').on(table.status),
])

export const rsiTestResults = pgTable('rsi_test_results', {
    id: uuid('id').defaultRandom().primaryKey(),
    proposalId: uuid('proposal_id')
        .notNull()
        .references(() => rsiProposals.id, { onDelete: 'cascade' }),
    taskId: text('task_id').references(() => tasks.id),
    isShadow: boolean('is_shadow').default(true).notNull(),
    baselineQuality: real('baseline_quality'),
    shadowQuality: real('shadow_quality'),
    tokenDelta: integer('token_delta'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('rsi_test_results_proposal_idx').on(table.proposalId),
])

// ── Phase 1 ─ Session Logs ────────────────────────────────────────────────────────
export const sessionLogs = pgTable('session_logs', {
    id: uuid('id').primaryKey().defaultRandom(),
    sessionId: uuid('session_id').notNull(),
    userId: uuid('user_id').references(() => users.id),
    personaId: varchar('persona_id', { length: 64 }),
    eventType: varchar('event_type', { length: 64 }).notNull(),
    route: varchar('route', { length: 512 }),
    action: varchar('action', { length: 256 }),
    payload: jsonb('payload'),
    responseCode: integer('response_code'),
    responseBody: jsonb('response_body'),
    errorMessage: text('error_message'),
    errorStack: text('error_stack'),
    durationMs: integer('duration_ms'),
    llmModel: varchar('llm_model', { length: 128 }),
    llmPromptTokens: integer('llm_prompt_tokens'),
    llmCompletionTokens: integer('llm_completion_tokens'),
    outputType: varchar('output_type', { length: 64 }),
    outputSummary: text('output_summary'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
})

// ── Artifacts System (Phase 4) ────────────────────────────────────────────────

export const artifacts = pgTable('artifacts', {
    id: text('id').primaryKey(), // ulid
    workspaceId: uuid('workspace_id')
        .notNull()
        .references(() => workspaces.id, { onDelete: 'cascade' }),
    taskId: text('task_id').references(() => tasks.id, { onDelete: 'set null' }),
    projectId: text('project_id').references(() => sprints.id, { onDelete: 'set null' }),
    filename: text('filename').notNull(),
    type: text('type').notNull(), // 'markdown' | 'code' | 'diagram' | 'html' | 'image' | 'file'
    currentVersion: integer('current_version').default(1).notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('artifacts_workspace_idx').on(table.workspaceId),
    index('artifacts_task_idx').on(table.taskId),
    index('artifacts_project_idx').on(table.projectId),
])

export const artifactVersions = pgTable('artifact_versions', {
    id: uuid('id').defaultRandom().primaryKey(),
    artifactId: text('artifact_id')
        .notNull()
        .references(() => artifacts.id, { onDelete: 'cascade' }),
    version: integer('version').notNull(),
    content: text('content').notNull(),
    changeDescription: text('change_description'),
    createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (table) => [
    index('artifact_versions_artifact_idx').on(table.artifactId),
    uniqueIndex('artifact_versions_artifact_version_uq').on(table.artifactId, table.version),
])
