import { useState, useEffect, useCallback } from 'react'
import { AlertCircle, CheckCircle, XCircle, FileText, Loader2, Play } from 'lucide-react'
import { useWorkspace } from '@web/context/workspace'

interface RSIProposal {
    id: string
    anomalyType: string
    hypothesis: string
    proposedChange: Record<string, unknown>
    risk: 'low' | 'medium' | 'high'
    status: 'pending' | 'approved' | 'rejected'
    createdAt: string
}

export function AccountabilityPanel() {
    const { workspaceId } = useWorkspace()
    const [proposals, setProposals] = useState<RSIProposal[]>([])
    const [loading, setLoading] = useState(false)
    const [actionLoading, setActionLoading] = useState<string | null>(null)
    const API_BASE = typeof window !== 'undefined' ? '' : (process.env.INTERNAL_API_URL || 'http://localhost:3001')
    const WS_ID = workspaceId || (process.env.NEXT_PUBLIC_DEFAULT_WORKSPACE ?? '')

    const loadProposals = useCallback(async () => {
        if (!WS_ID) return
        setLoading(true)
        try {
            const res = await fetch(`${API_BASE}/api/v1/workspaces/${WS_ID}/rsi/proposals`, { cache: 'no-store' })
            if (res.ok) {
                const data = await res.json()
                setProposals(data.items ?? [])
            }
        } catch {
            // Non-fatal
        } finally {
            setLoading(false)
        }
    }, [API_BASE, WS_ID])

    useEffect(() => {
        void loadProposals()
    }, [loadProposals])

    const handleAction = async (proposalId: string, action: 'approve' | 'reject') => {
        if (!WS_ID) return
        setActionLoading(proposalId)
        try {
            const res = await fetch(`${API_BASE}/api/v1/workspaces/${WS_ID}/rsi/proposals/${proposalId}/${action}`, {
                method: 'POST',
            })
            if (res.ok) {
                // Update local state without full reload
                const [updated] = await res.json() as [RSIProposal]
                if (updated) {
                    setProposals((prev) => prev.map((p) => p.id === proposalId ? { ...p, status: updated.status } : p))
                } else {
                    void loadProposals()
                }
            }
        } catch {
            // handle err
        } finally {
            setActionLoading(null)
        }
    }

    if (loading && proposals.length === 0) {
        return (
            <div className="flex flex-col gap-6">
                <div>
                    <h2 className="text-lg font-bold text-zinc-50">Accountability</h2>
                    <p className="mt-0.5 text-sm text-text-muted">Real-Time Self-Inspection (RSI) Proposals.</p>
                </div>
                <div className="flex items-center justify-center p-12">
                    <Loader2 className="h-4 w-4 animate-spin text-text-muted" />
                </div>
            </div>
        )
    }

    return (
        <div className="flex flex-col gap-6">
            <div>
                <h2 className="text-lg font-bold text-zinc-50">Accountability (RSI)</h2>
                <p className="mt-0.5 text-sm text-text-muted">Review and approve self-improvement proposals generated by the agent's RSI system.</p>
            </div>
            
            <div className="flex flex-col gap-4">
                {proposals.length === 0 ? (
                    <div className="rounded-xl border border-border bg-surface-1/40 p-8 flex flex-col items-center gap-3 text-center">
                        <FileText className="h-8 w-8 text-text-muted" />
                        <div>
                            <p className="text-sm font-medium text-text-secondary">No proposals available</p>
                            <p className="text-xs text-text-muted mt-1">The RSI system monitors behavior and will propose improvements here.</p>
                        </div>
                    </div>
                ) : (
                    proposals.map(p => (
                        <div key={p.id} className="rounded-xl border border-border bg-surface-1/60 overflow-hidden">
                            <div className="flex items-start justify-between p-4 border-b border-border-subtle">
                                <div>
                                    <div className="flex items-center gap-2 mb-1">
                                        <span className={`px-2 py-0.5 rounded text-[10px] font-mono font-medium tracking-wider
                                            ${p.anomalyType === 'cost_spikes' ? 'text-red bg-red/10' : 
                                              p.anomalyType === 'quality_degradation' ? 'text-yellow-400 bg-yellow-400/10' : 
                                              'text-blue-400 bg-blue-400/10'}
                                        `}>
                                            {p.anomalyType.replace('_', ' ').toUpperCase()}
                                        </span>
                                        <span className={`px-2 py-0.5 rounded text-[10px] uppercase font-medium tracking-wider
                                            ${p.status === 'pending' ? 'text-indigo bg-indigo-400/10' :
                                              p.status === 'approved' ? 'text-emerald bg-emerald/10' :
                                              'text-text-secondary bg-surface-2'}
                                        `}>
                                            {p.status}
                                        </span>
                                    </div>
                                    <h4 className="text-sm font-medium text-text-primary">{p.hypothesis}</h4>
                                </div>
                                <div className="text-right shrink-0">
                                    <p className="text-[10px] text-text-muted">{new Date(p.createdAt).toLocaleDateString()}</p>
                                    <p className="text-[10px] text-text-muted mt-0.5 capitalize">Risk: {p.risk}</p>
                                </div>
                            </div>
                            
                            <div className="p-4 bg-surface-1/40">
                                <p className="text-xs font-semibold text-text-secondary mb-2 uppercase tracking-wide">Proposed Protocol Change</p>
                                <pre className="text-xs text-indigo-300 font-mono overflow-auto bg-canvas p-3 rounded-lg border border-border/80">
                                    {JSON.stringify(p.proposedChange, null, 2)}
                                </pre>
                                
                                {p.status === 'pending' && (
                                    <div className="flex items-center gap-3 mt-4 pt-4 border-t border-border-subtle">
                                        <button 
                                            type="button"
                                            onClick={() => void handleAction(p.id, 'approve')}
                                            disabled={!!actionLoading}
                                            className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald px-3 py-2 text-xs font-medium border border-emerald-600/30 transition-colors disabled:opacity-50"
                                        >
                                            {actionLoading === p.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Play className="h-3.5 w-3.5" />}
                                            Run Shadow Mode
                                        </button>
                                        <button 
                                            type="button"
                                            onClick={() => void handleAction(p.id, 'reject')}
                                            disabled={!!actionLoading}
                                            className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-surface-2 hover:bg-zinc-700 text-text-secondary px-3 py-2 text-xs font-medium border border-border transition-colors disabled:opacity-50"
                                        >
                                            <XCircle className="h-3.5 w-3.5" />
                                            Dismiss Fluke
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    )
}
