// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Joeybuilt LLC

/**
 * digest-worker.ts — Weekly error digest: native analytics -> GitHub issue.
 *
 * Schedule: Monday 08:00 UTC (wired via cron.ts scheduler).
 *
 * Flow:
 *   1. Query plexo_ops_errors for unresolved errors (past 7 days, >=3 occurrences)
 *   2. Format as markdown table
 *   3. Create GitHub issue on joeybuilt-official/plexo
 *   4. On failure: write to dead letter table (analytics_digest_failures)
 */

import pino from 'pino'

const logger = pino({ name: 'analytics:digest-worker' })

export interface ErrorGroup {
    fingerprint: string
    message: string
    occurrenceCount: number
    firstSeenAt: string
    lastSeenAt: string
}

export interface DigestResult {
    issueCount: number
    githubIssueUrl: string | null
    error: string | null
}

async function queryNativeErrors(minOccurrences: number, maxItems: number): Promise<ErrorGroup[]> {
    try {
        const { db } = await import('@plexo/db')
        const { sql } = await import('drizzle-orm')
        const rows = await db.execute<{
            fingerprint: string; message: string
            occurrence_count: number; first_seen_at: string; last_seen_at: string
        }>(sql`
            SELECT fingerprint, message, occurrence_count, first_seen_at, last_seen_at
            FROM plexo_ops_errors
            WHERE resolved_at IS NULL
              AND last_seen_at >= NOW() - INTERVAL '7 days'
              AND occurrence_count >= ${minOccurrences}
            ORDER BY occurrence_count DESC
            LIMIT ${maxItems}
        `)
        return rows.map(r => ({
            fingerprint: r.fingerprint,
            message: r.message,
            occurrenceCount: r.occurrence_count,
            firstSeenAt: r.first_seen_at,
            lastSeenAt: r.last_seen_at,
        }))
    } catch (err) {
        logger.error({ err }, 'queryNativeErrors failed')
        return []
    }
}

function formatDigestBody(errors: ErrorGroup[], weekOf: string): string {
    if (errors.length === 0) {
        return `# Weekly Error Digest — ${weekOf}\n\nNo errors with >= 3 occurrences this week.`
    }

    const rows = errors.map(e =>
        `| ${e.message.slice(0, 80)} | ${e.fingerprint.slice(0, 40)} | ${e.occurrenceCount} | ${e.lastSeenAt.slice(0, 10)} |`,
    )

    return [
        `# Weekly Error Digest — ${weekOf}`,
        '',
        `${errors.length} error(s) with >= 3 occurrences in the past 7 days.`,
        '',
        '| Message | Fingerprint | Count | Last Seen |',
        '|---------|-------------|-------|-----------|',
        ...rows,
        '',
        '*Auto-generated by the analytics digest worker.*',
    ].join('\n')
}

async function createGitHubIssue(opts: {
    githubToken: string; owner: string; repo: string
    title: string; body: string; labels: string[]
}): Promise<string | null> {
    if (!opts.githubToken) {
        logger.warn('createGitHubIssue: GITHUB_TOKEN not set — skipping')
        return null
    }

    const res = await fetch(`https://api.github.com/repos/${opts.owner}/${opts.repo}/issues`, {
        method: 'POST',
        headers: {
            Authorization: `Bearer ${opts.githubToken}`,
            'content-type': 'application/json',
            Accept: 'application/vnd.github+json',
        },
        body: JSON.stringify({ title: opts.title, body: opts.body, labels: opts.labels }),
        signal: AbortSignal.timeout(15_000),
    })
    if (!res.ok) {
        throw new Error(`GitHub API returned ${res.status}: ${await res.text().catch(() => '(no body)')}`)
    }
    const data = await res.json() as { html_url?: string }
    return data.html_url ?? null
}

async function writeDeadLetter(opts: { weekOf: string; attempt: number; error: string }): Promise<void> {
    try {
        const { db } = await import('@plexo/db')
        const { sql } = await import('drizzle-orm')
        await db.execute(sql`
            INSERT INTO analytics_digest_failures (id, week_of, attempt, error)
            VALUES (gen_random_uuid(), ${opts.weekOf}, ${opts.attempt}, ${opts.error})
        `)
    } catch (err) {
        logger.error({ err, ...opts }, 'writeDeadLetter: failed to persist')
    }
}

/**
 * Query per-domain quality metrics for the domain mastery digest section.
 * Returns top domains by task count from the last week.
 */
async function queryDomainMetrics(): Promise<Array<{
    domain_tag: string; task_count: number; avg_quality: number | null; quality_delta: number | null
}>> {
    try {
        const { db } = await import('@plexo/db')
        const { sql } = await import('drizzle-orm')
        const rows = await db.execute<{
            domain_tag: string; task_count: number; avg_quality: number | null; quality_delta: number | null
        }>(sql`
            SELECT domain_tag, task_count, avg_quality, quality_delta
            FROM plexo_ops_domain_metrics
            WHERE period_start >= (CURRENT_DATE - INTERVAL '7 days')
            ORDER BY task_count DESC
            LIMIT 15
        `)
        return rows
    } catch {
        return []
    }
}

function formatDomainSection(domains: Array<{
    domain_tag: string; task_count: number; avg_quality: number | null; quality_delta: number | null
}>): string {
    if (domains.length === 0) return ''

    const rows = domains.map(d => {
        const q = d.avg_quality != null ? d.avg_quality.toFixed(2) : '—'
        const delta = d.quality_delta != null
            ? (d.quality_delta >= 0 ? `+${d.quality_delta.toFixed(2)}` : d.quality_delta.toFixed(2))
            : '—'
        return `| ${d.domain_tag} | ${d.task_count} | ${q} | ${delta} |`
    })

    return [
        '',
        '## Domain Quality (last 7 days)',
        '',
        '| Domain | Tasks | Avg Quality | Delta |',
        '|--------|-------|-------------|-------|',
        ...rows,
    ].join('\n')
}

export async function runWeeklyDigest(): Promise<DigestResult> {
    const weekOf = new Date().toISOString().slice(0, 10)
    const maxRetries = 3

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
            logger.info({ weekOf, attempt }, 'Running weekly error digest')

            const errors = await queryNativeErrors(3, 30)
            const domainMetrics = await queryDomainMetrics()
            const body = formatDigestBody(errors, weekOf) + formatDomainSection(domainMetrics)

            let githubIssueUrl: string | null = null
            if (errors.length > 0) {
                githubIssueUrl = await createGitHubIssue({
                    githubToken: process.env.GITHUB_TOKEN ?? '',
                    owner: process.env.GITHUB_DIGEST_OWNER ?? 'joeybuilt-official',
                    repo: process.env.GITHUB_DIGEST_REPO ?? 'plexo',
                    title: `Weekly Error Digest — ${weekOf}`,
                    body,
                    labels: ['auto-triage', 'analytics'],
                })
            }

            logger.info({ weekOf, issueCount: errors.length, githubIssueUrl }, 'Weekly digest completed')
            return { issueCount: errors.length, githubIssueUrl, error: null }
        } catch (err) {
            const errorMsg = err instanceof Error ? err.message : String(err)
            logger.error({ weekOf, attempt, err: errorMsg }, 'Weekly digest attempt failed')

            if (attempt === maxRetries) {
                await writeDeadLetter({ weekOf, attempt, error: errorMsg })
                return { issueCount: 0, githubIssueUrl: null, error: `All ${maxRetries} attempts failed. Last error: ${errorMsg}` }
            }

            await new Promise((resolve) => setTimeout(resolve, 30_000 * attempt))
        }
    }

    return { issueCount: 0, githubIssueUrl: null, error: 'Unexpected exit from retry loop' }
}
