// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Joeybuilt LLC

/**
 * digest-worker.ts — Weekly error digest: Sentry -> GitHub issue.
 *
 * Schedule: Monday 08:00 UTC (wired via Inngest job, not in this file).
 * This module contains the standalone logic so it can be tested without Inngest.
 *
 * Flow:
 *   1. Query Sentry API for new issue groups (past 7 days, >=3 occurrences)
 *   2. Rate limit: max 30 items per digest
 *   3. Format as markdown table
 *   4. Create GitHub issue on joeybuilt-official/plexo
 *   5. On failure: write to dead letter table (telemetry_digest_failures)
 *
 * Retry policy: 3 attempts with 15-minute exponential backoff.
 */

import pino from 'pino'

const logger = pino({ name: 'telemetry:digest-worker' })

// ── Types ───────────────────────────────────────────────────────────────────────

export interface SentryIssueGroup {
    id: string
    title: string
    culprit: string
    count: number
    firstSeen: string
    lastSeen: string
    permalink: string
}

export interface DigestResult {
    issueCount: number
    githubIssueUrl: string | null
    error: string | null
}

// ── Sentry API query ────────────────────────────────────────────────────────────

/**
 * Query Sentry API for issue groups from the past 7 days with >= minOccurrences.
 * Returns at most maxItems issues, sorted by count descending.
 */
async function querySentryIssues(opts: {
    sentryApiUrl: string
    sentryAuthToken: string
    sentryOrgSlug: string
    sentryProjectSlug: string
    minOccurrences: number
    maxItems: number
}): Promise<SentryIssueGroup[]> {
    // TODO: Implement actual Sentry API call
    // GET /api/0/projects/{org}/{project}/issues/?query=is:unresolved&sort=freq&statsPeriod=7d
    // Filter client-side for count >= minOccurrences
    // Return top maxItems by count
    //
    // Example:
    // const url = `${opts.sentryApiUrl}/api/0/projects/${opts.sentryOrgSlug}/${opts.sentryProjectSlug}/issues/`
    // const params = new URLSearchParams({
    //     query: 'is:unresolved',
    //     sort: 'freq',
    //     statsPeriod: '7d',
    //     limit: String(opts.maxItems * 2),  // fetch extra to filter
    // })
    // const res = await fetch(`${url}?${params}`, {
    //     headers: { Authorization: `Bearer ${opts.sentryAuthToken}` },
    //     signal: AbortSignal.timeout(10_000),
    // })
    // const issues = await res.json()
    // return issues
    //     .filter((i: any) => Number(i.count) >= opts.minOccurrences)
    //     .slice(0, opts.maxItems)
    //     .map((i: any) => ({
    //         id: i.id,
    //         title: i.title,
    //         culprit: i.culprit,
    //         count: Number(i.count),
    //         firstSeen: i.firstSeen,
    //         lastSeen: i.lastSeen,
    //         permalink: i.permalink,
    //     }))

    logger.warn('querySentryIssues: stub — not yet implemented')
    return []
}

// ── GitHub issue creation ───────────────────────────────────────────────────────

/**
 * Format issues into a markdown table for the GitHub issue body.
 */
function formatDigestBody(issues: SentryIssueGroup[], weekOf: string): string {
    if (issues.length === 0) {
        return `# Weekly Error Digest — ${weekOf}\n\nNo new issues with >= 3 occurrences this week.`
    }

    const rows = issues.map((i) =>
        `| [${i.title.slice(0, 80)}](${i.permalink}) | ${i.culprit.slice(0, 40)} | ${i.count} | ${i.lastSeen.slice(0, 10)} |`,
    )

    return [
        `# Weekly Error Digest — ${weekOf}`,
        '',
        `${issues.length} issue(s) with >= 3 occurrences in the past 7 days.`,
        '',
        '| Issue | Culprit | Count | Last Seen |',
        '|-------|---------|-------|-----------|',
        ...rows,
        '',
        '*Auto-generated by the telemetry digest worker.*',
    ].join('\n')
}

/**
 * Create a GitHub issue with the digest content.
 */
async function createGitHubIssue(opts: {
    githubToken: string
    owner: string
    repo: string
    title: string
    body: string
    labels: string[]
}): Promise<string | null> {
    // TODO: Implement actual GitHub API call
    // POST /repos/{owner}/{repo}/issues
    //
    // Example:
    // const res = await fetch(`https://api.github.com/repos/${opts.owner}/${opts.repo}/issues`, {
    //     method: 'POST',
    //     headers: {
    //         Authorization: `Bearer ${opts.githubToken}`,
    //         'content-type': 'application/json',
    //         Accept: 'application/vnd.github+json',
    //     },
    //     body: JSON.stringify({
    //         title: opts.title,
    //         body: opts.body,
    //         labels: opts.labels,
    //     }),
    //     signal: AbortSignal.timeout(10_000),
    // })
    // const data = await res.json()
    // return data.html_url ?? null

    logger.warn('createGitHubIssue: stub — not yet implemented')
    return null
}

// ── Dead letter ─────────────────────────────────────────────────────────────────

/**
 * Write a failed digest attempt to the dead letter table for later retry/inspection.
 */
async function writeDeadLetter(opts: {
    weekOf: string
    attempt: number
    error: string
}): Promise<void> {
    // TODO: Implement DB write to telemetry_digest_failures table
    //
    // Schema:
    //   id         UUID PRIMARY KEY DEFAULT gen_random_uuid()
    //   week_of    TEXT NOT NULL
    //   attempt    INTEGER NOT NULL
    //   error      TEXT NOT NULL
    //   created_at TIMESTAMPTZ DEFAULT NOW()
    //
    // Example:
    // const { db, sql } = await import('@plexo/db')
    // await db.execute(sql`
    //     INSERT INTO telemetry_digest_failures (week_of, attempt, error)
    //     VALUES (${opts.weekOf}, ${opts.attempt}, ${opts.error})
    // `)

    logger.warn({ ...opts }, 'writeDeadLetter: stub — not yet implemented')
}

// ── Main entry point ────────────────────────────────────────────────────────────

/**
 * Run the weekly error digest.
 *
 * Queries Sentry for new issues, creates a GitHub issue with the summary,
 * and writes to the dead letter table on failure.
 *
 * Designed to be called from an Inngest scheduled function or standalone tests.
 *
 * Required env vars:
 *   SENTRY_API_URL         — e.g., https://sentry.getplexo.com
 *   SENTRY_AUTH_TOKEN       — Sentry internal API token
 *   SENTRY_ORG_SLUG         — e.g., joeybuilt
 *   SENTRY_PROJECT_SLUG     — e.g., plexo
 *   GITHUB_TOKEN            — GitHub PAT with repo:issues scope
 *   GITHUB_DIGEST_OWNER     — e.g., joeybuilt-official
 *   GITHUB_DIGEST_REPO      — e.g., plexo
 */
export async function runWeeklyDigest(): Promise<DigestResult> {
    const weekOf = new Date().toISOString().slice(0, 10)
    const maxRetries = 3
    const backoffMinutes = 15

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
            logger.info({ weekOf, attempt }, 'Running weekly error digest')

            // 1. Query Sentry
            const issues = await querySentryIssues({
                sentryApiUrl: process.env.SENTRY_API_URL ?? 'https://sentry.getplexo.com',
                sentryAuthToken: process.env.SENTRY_AUTH_TOKEN ?? '',
                sentryOrgSlug: process.env.SENTRY_ORG_SLUG ?? 'joeybuilt',
                sentryProjectSlug: process.env.SENTRY_PROJECT_SLUG ?? 'plexo',
                minOccurrences: 3,
                maxItems: 30,
            })

            // 2. Format digest body
            const body = formatDigestBody(issues, weekOf)

            // 3. Create GitHub issue
            const githubIssueUrl = await createGitHubIssue({
                githubToken: process.env.GITHUB_TOKEN ?? '',
                owner: process.env.GITHUB_DIGEST_OWNER ?? 'joeybuilt-official',
                repo: process.env.GITHUB_DIGEST_REPO ?? 'plexo',
                title: `Weekly Error Digest — ${weekOf}`,
                body,
                labels: ['auto-triage', 'from-sentry'],
            })

            logger.info({ weekOf, issueCount: issues.length, githubIssueUrl }, 'Weekly digest completed')

            return {
                issueCount: issues.length,
                githubIssueUrl,
                error: null,
            }
        } catch (err) {
            const errorMsg = err instanceof Error ? err.message : String(err)
            logger.error({ weekOf, attempt, err: errorMsg }, 'Weekly digest attempt failed')

            if (attempt === maxRetries) {
                // Final attempt failed — write to dead letter table
                await writeDeadLetter({
                    weekOf,
                    attempt,
                    error: errorMsg,
                })

                return {
                    issueCount: 0,
                    githubIssueUrl: null,
                    error: `All ${maxRetries} attempts failed. Last error: ${errorMsg}`,
                }
            }

            // Wait before retrying (exponential backoff)
            const delayMs = backoffMinutes * 60_000 * attempt
            logger.info({ nextAttemptIn: `${backoffMinutes * attempt}m` }, 'Retrying after backoff')
            await new Promise((resolve) => setTimeout(resolve, delayMs))
        }
    }

    // Unreachable, but TypeScript needs it
    return { issueCount: 0, githubIssueUrl: null, error: 'Unexpected exit from retry loop' }
}
