-- Seed connections_registry with core integrations
-- Run once: cat this file | docker exec -i <postgres> psql -U plexo -d plexo

INSERT INTO connections_registry
    (id, name, description, category, logo_url, auth_type, oauth_scopes, setup_fields, tools_provided, cards_provided, is_core, doc_url, created_at)
VALUES
    (
        'github',
        'GitHub',
        'Interact with repositories, issues, pull requests, and GitHub Actions.',
        'code',
        'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        'oauth2',
        '["repo", "read:org", "workflow"]',
        '[]',
        '["create_branch", "open_pr", "merge_pr", "list_issues", "create_issue", "get_ci_status"]',
        '["github_activity", "open_prs"]',
        true,
        'https://docs.github.com/en/rest',
        now()
    ),
    (
        'slack',
        'Slack',
        'Receive tasks from Slack DMs and slash commands, post results back to channels.',
        'communication',
        'https://a.slack-edge.com/80588/marketing/img/meta/slack_hash_256.png',
        'oauth2',
        '["chat:write", "commands", "im:history"]',
        '[]',
        '["send_message", "post_to_channel"]',
        '["slack_activity"]',
        true,
        'https://api.slack.com',
        now()
    ),
    (
        'discord',
        'Discord',
        'Accept /task slash commands in your Discord server and receive results.',
        'communication',
        'https://cdn.simpleicons.org/discord/5865F2',
        'webhook',
        '[]',
        '[{"key":"public_key","label":"Public Key","type":"password"},{"key":"application_id","label":"Application ID","type":"text"},{"key":"bot_token","label":"Bot Token","type":"password"}]',
        '["queue_task"]',
        '[]',
        true,
        'https://discord.com/developers/docs',
        now()
    ),
    (
        'telegram',
        'Telegram',
        'Receive tasks via Telegram bot DMs and group commands.',
        'communication',
        'https://telegram.org/img/t_logo.png',
        'api_key',
        '[]',
        '[{"key":"bot_token","label":"Bot Token","type":"password"}]',
        '["send_message"]',
        '[]',
        true,
        'https://core.telegram.org/bots/api',
        now()
    ),
    (
        'openai',
        'OpenAI',
        'Use OpenAI embeddings for semantic memory search (text-embedding-3-small).',
        'ai',
        'https://openai.com/favicon.ico',
        'api_key',
        '[]',
        '[{"key":"api_key","label":"API Key","type":"password"}]',
        '["embed_text"]',
        '[]',
        false,
        'https://platform.openai.com/docs',
        now()
    ),
    (
        'linear',
        'Linear',
        'Sync tasks with Linear issues. Create, update, and comment on Linear issues from the agent.',
        'project-management',
        'https://linear.app/favicon.ico',
        'oauth2',
        '["read", "write", "issues:create"]',
        '[]',
        '["create_issue", "update_issue", "add_comment"]',
        '["linear_issues"]',
        false,
        'https://developers.linear.app',
        now()
    ),
    (
        'jira',
        'Jira',
        'Create and update Jira tickets from tasks. Link agent work to your existing Jira projects.',
        'project-management',
        'https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png',
        'oauth2',
        '["read:jira-work", "write:jira-work"]',
        '[]',
        '["create_issue", "update_issue", "add_comment"]',
        '["jira_issues"]',
        false,
        'https://developer.atlassian.com/cloud/jira',
        now()
    ),
    (
        'notion',
        'Notion',
        'Read and write to Notion databases. Store research outputs, specs, and reports.',
        'knowledge',
        'https://www.notion.so/images/favicon.ico',
        'oauth2',
        '["read_content", "update_content", "insert_content"]',
        '[]',
        '["create_page", "update_page", "search_pages"]',
        '["notion_pages"]',
        false,
        'https://developers.notion.com',
        now()
    ),
    (
        'pagerduty',
        'PagerDuty',
        'Trigger and resolve PagerDuty incidents automatically from monitoring tasks.',
        'ops',
        'https://www.pagerduty.com/favicon.ico',
        'api_key',
        '[]',
        '[{"key":"api_key","label":"API Key","type":"password"},{"key":"service_id","label":"Service ID","type":"text"}]',
        '["trigger_incident", "resolve_incident", "add_note"]',
        '["incident_status"]',
        false,
        'https://developer.pagerduty.com',
        now()
    ),
    (
        'datadog',
        'Datadog',
        'Query metrics, logs, and traces. Use in monitoring and ops tasks.',
        'observability',
        'https://imgix.datadoghq.com/img/dd_logo_n_70x75.png',
        'api_key',
        '[]',
        '[{"key":"api_key","label":"API Key","type":"password"},{"key":"app_key","label":"App Key","type":"password"}]',
        '["query_metrics", "query_logs", "create_event"]',
        '["metrics_graph"]',
        false,
        'https://docs.datadoghq.com/api',
        now()
    )
ON CONFLICT (id) DO NOTHING;
