// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Joeybuilt LLC

/**
 * Environment Validation — fail-fast at startup
 *
 * Called before any network binding or DB connection.
 * Exits the process with code 1 on missing required vars,
 * with a clear message listing exactly what's missing.
 *
 * Required vs. optional:
 *   Required  — process won't function at all without these
 *   Optional  — features degrade gracefully (AI providers, OAuth)
 *   Warned    — wrong format but not fatal
 */

interface EnvVar {
    key: string
    description: string
    /** If true, process exits if missing. If false, logs a warning. */
    required: boolean
    /** If provided, also validates format */
    validate?: (val: string) => boolean
    validateMsg?: string
}

const ENV_SPEC: EnvVar[] = [
    // ── Required ──────────────────────────────────────────────────────────────
    {
        key: 'DATABASE_URL',
        description: 'PostgreSQL connection string',
        required: true,
        validate: (v) => v.startsWith('postgresql://') || v.startsWith('postgres://'),
        validateMsg: 'Must start with postgresql:// or postgres://',
    },
    {
        key: 'REDIS_URL',
        description: 'Redis connection string',
        required: true,
        validate: (v) => v.startsWith('redis://') || v.startsWith('rediss://'),
        validateMsg: 'Must start with redis:// or rediss://',
    },
    {
        key: 'SESSION_SECRET',
        description: 'Session encryption secret (generate: openssl rand -hex 64)',
        required: true,
        validate: (v) => v.length >= 32,
        validateMsg: 'Must be at least 32 characters',
    },
    {
        key: 'ENCRYPTION_SECRET',
        description: 'AES-256-GCM root key for credential encryption (generate: openssl rand -hex 32)',
        required: true,
        validate: (v) => v.length >= 32,
        validateMsg: 'Must be at least 32 characters — generate with: openssl rand -hex 32',
    },
    // ── Required — Supabase Auth (shared joeybuilt-platform instance) ───────────
    {
        key: 'SUPABASE_JWT_SECRET',
        description: 'JWT secret from the shared Supabase project (Settings → API → JWT Secret)',
        required: true,
        validate: (v) => v.length >= 20,
        validateMsg: 'Must be at least 20 characters',
    },
    // ── Optional — Supabase (for server-side admin operations) ─────────────────
    {
        key: 'SUPABASE_URL',
        description: 'Supabase project URL (for admin SDK usage)',
        required: false,
    },
    {
        key: 'SUPABASE_SERVICE_ROLE_KEY',
        description: 'Supabase service role key (server-side only)',
        required: false,
    },
    // ── Optional — Service key for app↔Plexo communication ────────────────────
    {
        key: 'PLEXO_SERVICE_KEY',
        description: 'Shared secret for Joeybuilt app↔Plexo service-to-service auth',
        required: false,
        validate: (v) => v.length >= 32,
        validateMsg: 'Must be at least 32 characters — generate with: openssl rand -hex 32',
    },
    // ── Optional — CORS ───────────────────────────────────────────────────────
    {
        key: 'CORS_ORIGINS',
        description: 'Comma-separated list of allowed CORS origins (e.g., https://command.joeybuilt.com,https://fylo.joeybuilt.com)',
        required: false,
    },
    // ── Optional — AI providers (configured per-workspace in the UI) ────────────
    {
        key: 'OPENAI_API_KEY',
        description: 'OpenAI API key (env-level fallback; prefer workspace UI config)',
        required: false,
    },
    // ── Optional — Synthesizer ────────────────────────────────────────────────
    {
        key: 'GENERATED_SKILLS_DIR',
        description: 'Writable directory for agent-generated extensions (default: /var/plexo/generated-skills)',
        required: false,
    },
    // ── Optional — Error tracking ─────────────────────────────────────────────
    {
        key: 'SENTRY_DSN',
        description: 'Sentry DSN for error reporting (https://sentry.io or self-hosted)',
        required: false,
    },
    // ── Optional — Asset storage ──────────────────────────────────────────────
    {
        key: 'STORAGE_ACCESS_KEY',
        description: 'MinIO/S3 access key for agent asset storage (auto-configured by Docker Compose)',
        required: false,
    },
    {
        key: 'STORAGE_SECRET_KEY',
        description: 'MinIO/S3 secret key for agent asset storage (generate: openssl rand -hex 32)',
        required: false,
    },
    // ── Optional — Observability ──────────────────────────────────────────────
    {
        key: 'POSTHOG_API_KEY',
        description: 'PostHog API key for anonymous product telemetry',
        required: false,
    },
    {
        key: 'PLEXO_INSTANCE_ID',
        description: 'Unique identifier for this Plexo instance (auto-generated by install.sh)',
        required: false,
    },
    {
        key: 'DEBUG_TOKEN',
        description: 'Secret token to access /api/debug/* in production',
        required: false,
        validate: (v) => v.length >= 24,
        validateMsg: 'DEBUG_TOKEN must be at least 24 characters',
    },
]

export function validateEnv(): void {
    const errors: string[] = []
    const warnings: string[] = []

    for (const spec of ENV_SPEC) {
        const val = process.env[spec.key]

        if (!val) {
            if (spec.required) {
                errors.push(`  ✗ ${spec.key} — ${spec.description}`)
            } else {
                warnings.push(`  ⚠ ${spec.key} not set — ${spec.description}`)
            }
            continue
        }

        if (spec.validate && !spec.validate(val)) {
            const msg = `  ✗ ${spec.key} — ${spec.validateMsg ?? 'invalid format'}`
            if (spec.required) {
                errors.push(msg)
            } else {
                warnings.push(msg)
            }
        }
    }

    // AI provider keys are optional at the env level — they can be configured
    // per-workspace in the UI. A missing env-level key is not a startup error.

    // Print warnings (non-fatal)
    if (warnings.length > 0) {
        console.warn('[env] Missing optional configuration:')
        for (const w of warnings) console.warn(w)
    }

    // Exit on errors (fatal)
    if (errors.length > 0) {
        console.error('[env] FATAL — Missing required environment variables:')
        for (const e of errors) console.error(e)
        console.error('\nSet these in .env (root of the repo). See .env.example for descriptions and generation commands.')
        console.error('See .env.example for descriptions and generation commands.')
        process.exit(1)
    }
}
