#!/usr/bin/env bash
# Pre-flight for authoring a new drizzle migration (0118+).
#
# Surfaces the three numbers an author needs to set the new journal entry's
# `when` correctly under the drizzle MAX(created_at) skip-cursor invariant:
#
#   prod_max             — current MAX(__drizzle_migrations.created_at) on prod
#   local_journal_max    — max `when` across packages/db/drizzle/meta/_journal.json
#   recommended_next_when= max(prod_max, local_journal_max) + 60_000
#                          (matches the 0116 -> 0117 +60s convention).
#
# Background: see PHASE-6-OPS.md §3.3 for why hand-editing journal `when` is
# sometimes required (drizzle-kit defaults to `when=Date.now()`, which would
# fall below the future-dated 0112-0117 entries until 2026-05-20).
#
# Usage:
#   bash scripts/next-migration-when.sh
#
# Env overrides:
#   PLEXO_VPS_HOST   default root@203.0.113.10
#   PLEXO_VPS_KEY    default ~/.ssh/joeybuilt_vps
#
# Exit codes:
#   0  green — `recommended_next_when` is strictly greater than prod_max.
#   1  red — could not reach prod, or prod_max already exceeds the recommended
#            value (would mean the journal is more than 60s behind prod, which
#            indicates a different kind of drift — investigate before authoring).

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JOURNAL="$ROOT/packages/db/drizzle/meta/_journal.json"

VPS="${PLEXO_VPS_HOST:-root@203.0.113.10}"
KEY="${PLEXO_VPS_KEY:-$HOME/.ssh/joeybuilt_vps}"

if [ ! -f "$JOURNAL" ]; then
    echo "ERR: $JOURNAL not found — run from the plexo repo root." >&2
    exit 1
fi

prod_max=$(ssh -o ConnectTimeout=10 -i "$KEY" "$VPS" \
    "docker exec postgres psql -U postgres -d plexo -t -A \
       -c \"SELECT COALESCE(MAX(created_at), 0) FROM drizzle.__drizzle_migrations;\"" \
    2>/dev/null | tr -d '[:space:]')

if [ -z "${prod_max:-}" ]; then
    echo "ERR: could not reach prod via $VPS (key=$KEY)." >&2
    exit 1
fi

local_max=$(python3 -c "
import json
with open('$JOURNAL') as f:
    print(max(e.get('when', 0) for e in json.load(f)['entries']))
")

base=$(( prod_max > local_max ? prod_max : local_max ))
next=$(( base + 60000 ))

ts_human() {
    local ms=$1
    local s=$(( ms / 1000 ))
    date -u -d "@$s" '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null || \
        date -u -r "$s" '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null || echo "(date unavailable)"
}

printf 'prod_max               = %s   # %s\n' "$prod_max"  "$(ts_human "$prod_max")"
printf 'local_journal_max      = %s   # %s\n' "$local_max" "$(ts_human "$local_max")"
printf 'recommended_next_when  = %s   # %s   (= max(prod, local) + 60_000 ms)\n' \
    "$next" "$(ts_human "$next")"

now_ms=$(( $(date -u +%s) * 1000 ))
if [ "$now_ms" -lt "$base" ]; then
    echo
    echo "WARN: drizzle-kit's auto-generated when=Date.now() ($now_ms) is below the"
    echo "      current max ($base). A migration generated by drizzle-kit RIGHT NOW"
    echo "      would be silently skipped by the MAX(created_at) cursor. Hand-edit"
    echo "      packages/db/drizzle/meta/_journal.json so the new entry's \`when\`"
    echo "      is set to $next (or any value strictly greater than $base)."
fi

if [ "$next" -le "$prod_max" ]; then
    echo "ERR: recommended_next_when ($next) <= prod_max ($prod_max). Investigate." >&2
    exit 1
fi

exit 0
