#!/usr/bin/env sh
# Regenerate every tool-native agent file so each is SELF-CONTAINED. Two sources of truth, rendered
# out — never hand-duplicated:
#   * the universal preamble  = the MIRROR block in AGENTS.md (read-order + non-negotiables + guardrails)
#   * the rule bodies         = the full text of every .claude/rules/*.md module
# Each mirror INLINES the preamble followed by the complete body of every rule module, so a tool that
# only loads its own native file (Cursor, Copilot, Windsurf, Cline, Gemini, aider, Codex) gets the WHOLE
# ruleset — never a pointer to .claude/rules/ it cannot follow. AGENTS.md is refilled in place too, between
# its <!-- PANOPLY:RULES:BEGIN/END --> markers, so AGENTS.md-native tools get the full governance with no
# @-imports. Never hand-edit a mirror or the AGENTS.md rules block; edit AGENTS.md (preamble) or
# .claude/rules/*.md (bodies) and re-run. POSIX sh, no runtime deps — Git Bash, WSL, macOS, Linux, CI.
#   sh scripts/sync-agents.sh              # write mirrors + refill AGENTS.md rules block
#   sh scripts/sync-agents.sh --check      # exit 1 if any mirror / the AGENTS.md block is stale (CI gate)
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/AGENTS.md"
RULES_DIR="$ROOT/.claude/rules"
[ -f "$SRC" ] || { echo "AGENTS.md not found; run /adapt-claude-setup first." >&2; exit 1; }
[ -d "$RULES_DIR" ] || { echo ".claude/rules/ not found." >&2; exit 1; }

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# --- The rule modules, in read order. Curated order first (clean-architecture is the premise every
#     other module inherits from), then any other .claude/rules/*.md not listed, so a newly added module
#     is never silently dropped. Missing modules (pruned by /adapt) are skipped. ---
ORDER="clean-architecture workflow quality-bar git-workflow documentation code-style testing error-handling database data-modeling api-design frontend design-system ai-features"
MODULES=""
for m in $ORDER; do
  [ -f "$RULES_DIR/$m.md" ] && MODULES="$MODULES $m"
done
for f in "$RULES_DIR"/*.md; do
  [ -f "$f" ] || continue
  b="$(basename "$f" .md)"
  case " $MODULES " in *" $b "*) ;; *) MODULES="$MODULES $b" ;; esac
done
[ -n "$MODULES" ] || { echo "No rule modules under .claude/rules/." >&2; exit 1; }

# The universal preamble body: the MIRROR block extracted from AGENTS.md (single source of truth).
MIRROR="$(awk '/MIRROR:start/{f=1;next} /MIRROR:end/{f=0} f' "$SRC")"
[ -n "$MIRROR" ] || { echo "No MIRROR block found in AGENTS.md." >&2; exit 1; }

GEN="<!-- GENERATED by scripts/sync-agents.sh from AGENTS.md + .claude/rules/*.md — DO NOT EDIT. Edit AGENTS.md (preamble) or .claude/rules/*.md (rule bodies) and re-run \`sh scripts/sync-agents.sh\`. -->"
NOTE="> **This file is self-contained.** It reproduces the COMPLETE ruleset for this repo — the universal
> preamble below, then the full text of every \`.claude/rules/\` module — so you can follow it without
> opening any other file. It is generated; do not edit it. Edit \`AGENTS.md\` (the preamble) or
> \`.claude/rules/*.md\` (the rule bodies) and run \`sh scripts/sync-agents.sh\`."

TMP="$(mktemp)"
RULESTMP="$(mktemp)"
trap 'rm -f "$TMP" "$RULESTMP"' EXIT INT TERM

# Concatenate every rule module's full body, separated by an hr.
render_rules() {
  _first=1
  for m in $MODULES; do
    if [ "$_first" -eq 1 ]; then _first=0; else printf '\n---\n\n'; fi
    cat "$RULES_DIR/$m.md"
  done
}
render_rules > "$RULESTMP"

STALE=0
# Compare TMP against the on-disk target (check mode) or install it (write mode).
put() { # $1 = repo-relative path
  dst="$ROOT/$1"
  if [ "$CHECK" -eq 1 ]; then
    if [ ! -f "$dst" ] || ! diff -q "$TMP" "$dst" >/dev/null 2>&1; then
      echo "STALE: $1"; STALE=1
    fi
  else
    mkdir -p "$(dirname "$dst")"
    cp "$TMP" "$dst"
    echo "wrote $1"
  fi
}

# A concatenated mirror = frontmatter (optional) + preamble + every rule body inlined.
build_mirror() { # $1 = optional frontmatter
  {
    [ -n "${1:-}" ] && printf '%s\n' "$1"
    printf '%s\n\n' "$GEN"
    printf '%s\n\n' "$NOTE"
    printf '%s\n\n' "$MIRROR"
    printf '%s\n\n' "---"
    cat "$RULESTMP"
  } > "$TMP"
}

# --- Concatenated, single-file mirrors (preamble + all rule bodies) ---
build_mirror ""                        ; put ".github/copilot-instructions.md"
build_mirror ""                        ; put "GEMINI.md"
build_mirror ""                        ; put "CONVENTIONS.md"                       # aider
build_mirror ""                        ; put ".clinerules/00-agents.md"
build_mirror "---
trigger: always_on
---"                                    ; put ".windsurf/rules/00-agents.md"

# --- Cursor: one .mdc per rule module (alwaysApply), plus a preamble file. All load together, so the
#     set is self-contained; each module file carries its own full body verbatim. ---
build_cursor_preamble() {
  {
    printf '%s\n' "---"
    printf 'description: %s\n' "Panoply — universal preamble & read-order (all rule modules load alongside this)"
    printf 'alwaysApply: true\n'
    printf '%s\n\n' "---"
    printf '%s\n\n' "$GEN"
    printf '%s\n\n' "$NOTE"
    printf '%s\n' "$MIRROR"
  } > "$TMP"
}
build_cursor_module() { # $1 = module basename
  title="$(sed -n 's/^# //p' "$RULES_DIR/$1.md" | head -1)"
  [ -n "$title" ] || title="$1"
  {
    printf '%s\n' "---"
    printf 'description: %s\n' "Panoply rule — $title (read 00-preamble.mdc first for the read-order)"
    printf 'alwaysApply: true\n'
    printf '%s\n\n' "---"
    printf '%s\n\n' "$GEN"
    cat "$RULES_DIR/$1.md"
  } > "$TMP"
}
build_cursor_preamble ; put ".cursor/rules/00-preamble.mdc"
for m in $MODULES; do
  build_cursor_module "$m" ; put ".cursor/rules/$m.mdc"
done

# Prune Cursor .mdc files we previously generated whose module no longer exists (e.g. pruned by /adapt,
# or the old single 00-agents.mdc layout). Only touch files bearing our GENERATED marker.
DESIRED="00-preamble"
for m in $MODULES; do DESIRED="$DESIRED $m"; done
if [ -d "$ROOT/.cursor/rules" ]; then
  for f in "$ROOT"/.cursor/rules/*.mdc; do
    [ -f "$f" ] || continue
    b="$(basename "$f" .mdc)"
    case " $DESIRED " in *" $b "*) continue ;; esac
    grep -q 'GENERATED by scripts/sync-agents.sh' "$f" 2>/dev/null || continue
    if [ "$CHECK" -eq 1 ]; then
      echo "STALE (orphan): .cursor/rules/$b.mdc"; STALE=1
    else
      rm -f "$f"; echo "removed orphan .cursor/rules/$b.mdc"
    fi
  done
fi

# --- AGENTS.md: refill the full rule bodies between the PANOPLY:RULES markers (self-contained, no
#     @-imports), preserving all hand-authored content outside the block. ---
grep -q 'PANOPLY:RULES:BEGIN' "$SRC" && grep -q 'PANOPLY:RULES:END' "$SRC" || {
  echo "AGENTS.md is missing the <!-- PANOPLY:RULES:BEGIN/END --> markers." >&2; exit 1
}
awk -v rules="$RULESTMP" '
  /PANOPLY:RULES:BEGIN/ { print; print ""; while ((getline line < rules) > 0) print line; print ""; skip=1; next }
  /PANOPLY:RULES:END/   { skip=0; print; next }
  skip { next }
  { print }
' "$SRC" > "$TMP"
if [ "$CHECK" -eq 1 ]; then
  if ! diff -q "$TMP" "$SRC" >/dev/null 2>&1; then echo "STALE: AGENTS.md (rules block)"; STALE=1; fi
else
  cp "$TMP" "$SRC"; echo "refilled AGENTS.md rules block"
fi

if [ "$CHECK" -eq 1 ]; then
  [ "$STALE" -eq 0 ] && { echo "Mirrors + AGENTS.md in sync with the preamble and rule modules."; exit 0; }
  echo "Mirrors are stale — run: sh scripts/sync-agents.sh" >&2; exit 1
fi
echo "Mirrors regenerated (self-contained) from AGENTS.md + .claude/rules/*.md."