#!/usr/bin/env sh
# Regenerate every tool-native agent file from AGENTS.md. ONE source of truth: AGENTS.md.
# Each mirror = a pointer to AGENTS.md + the MIRROR block extracted from AGENTS.md (the "if you read
# nothing else" onboarding contract + hard guardrails). Never hand-edit a mirror; edit AGENTS.md and
# re-run. POSIX sh, no runtime deps — works in Git Bash, WSL, macOS, Linux, and CI for any stack.
#   sh scripts/sync-agents.sh              # write mirrors
#   sh scripts/sync-agents.sh --check      # exit 1 if any mirror is stale (CI / pre-commit gate)
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/AGENTS.md"
[ -f "$SRC" ] || { echo "AGENTS.md not found; run /adapt-claude-setup first." >&2; exit 1; }

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# The shared block, extracted from AGENTS.md between the MIRROR markers (single source of truth).
# It carries the onboarding read-order + carry-work-forward line + the hard guardrails, so a tool
# that loads its always-applied rules file but never opens AGENTS.md still gets all of them.
MIRROR="$(awk '/MIRROR:start/{f=1;next} /MIRROR:end/{f=0} f' "$SRC")"
[ -n "$MIRROR" ] || { echo "No MIRROR block found in AGENTS.md." >&2; exit 1; }

GEN="<!-- GENERATED by scripts/sync-agents.sh from AGENTS.md — DO NOT EDIT. Edit AGENTS.md and re-run \`sh scripts/sync-agents.sh\`. -->"
POINTER="This repository's canonical agent instructions live in **AGENTS.md** at the repo root.
Read AGENTS.md first — it carries the full onboarding read-order, points to the deep rules in
\`.claude/rules/\` and the live plan in \`docs/claude/roadmap.md\` + \`docs/claude/in-progress.md\`.
The essentials are repeated below so they stay in context even if AGENTS.md is not opened."

render() { # $1 = optional frontmatter -> full file body on stdout
  [ -n "${1:-}" ] && printf '%s\n' "$1"
  printf '%s\n\n%s\n\n%s\n' "$GEN" "$POINTER" "$MIRROR"
}

STALE=0
emit() { # $1=path  $2=frontmatter(optional)
  dst="$ROOT/$1"
  if [ "$CHECK" -eq 1 ]; then
    if [ ! -f "$dst" ] || ! render "${2:-}" | diff -q - "$dst" >/dev/null 2>&1; then
      echo "STALE: $1"; STALE=1
    fi
  else
    mkdir -p "$(dirname "$dst")"
    render "${2:-}" > "$dst"
    echo "wrote $1"
  fi
}

emit ".github/copilot-instructions.md"
emit ".clinerules/00-agents.md"
emit "GEMINI.md"
emit "CONVENTIONS.md"                                                   # aider
emit ".cursor/rules/00-agents.mdc"  "---
description: Canonical agent rules (see AGENTS.md)
alwaysApply: true
---"
emit ".windsurf/rules/00-agents.md" "---
trigger: always_on
---"

if [ "$CHECK" -eq 1 ]; then
  [ "$STALE" -eq 0 ] && { echo "Mirrors in sync with AGENTS.md."; exit 0; }
  echo "Mirrors are stale — run: sh scripts/sync-agents.sh" >&2; exit 1
fi
echo "Mirrors regenerated from AGENTS.md."
